# Generated by Django 5.1.5 on 2025-02-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_item_slug_pokemon_slug_synergy_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='picture',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='alternate_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
