# Generated by Django 5.1.5 on 2025-02-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_pokemon_picture_pokemon_alternate_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='unite_move_activation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='alternate_names',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack_speed',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='critical_hit_damage_bonus_rate',
            field=models.IntegerField(blank=True, default='', help_text='Percentage value (e.g., 20 for 20%)'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='critical_hit_rate',
            field=models.IntegerField(blank=True, default='', help_text='Percentage value (e.g., 10 for 10%)'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_attack',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_defense',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
