# Generated by Django 5.1.5 on 2025-03-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_pokemon_unite_move_activation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ability_1_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ability_pictures/'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='ability_2_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ability_pictures/'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='mp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='recommended_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=1),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='unite_move_picture',
            field=models.ImageField(blank=True, null=True, upload_to='move_pictures/'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='critical_hit_damage_bonus_rate',
            field=models.IntegerField(blank=True, default=0, help_text='Percentage value (e.g., 20 for 20%)'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='critical_hit_rate',
            field=models.IntegerField(blank=True, default=0, help_text='Percentage value (e.g., 10 for 10%)'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_attack',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='special_defense',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='tier',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
