# Generated by Django 5.1.7 on 2025-03-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='recommended_itemsSheep',
            field=models.ManyToManyField(blank=True, related_name='pokemon_recommended_sheep', to='catalogue.item'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='recommended_itemsSheepBold',
            field=models.ManyToManyField(blank=True, related_name='pokemon_recommended_sheep_bold', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='recommended_items',
            field=models.ManyToManyField(blank=True, related_name='pokemon_recommended', to='catalogue.item'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='recommended_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
